import type { BuiltinGuestLocale, GuestLocaleKey } from './guestLocale';

export const BUILTIN_PORTAL_MESSAGES: Record<BuiltinGuestLocale, Record<GuestLocaleKey, string>> = {
  en: {
    welcomeTo: 'Welcome to',
    map: 'Map',
    mapTitle: 'Your stay',
    mapSubtitle: 'Property location',
    openInMaps: 'Open in Google Maps',
    getDirections: 'Get directions',
    close: 'Close',
    propertyLocation: 'Property location',
    liveLikeLocal: 'Live like a local',
    liveLikeLocalSub:
      'Plan your day with AI: restaurants, beaches, trails, and your host’s favourite local spots nearby.',
    liveLikeLocalHero: 'Live like a local',
    liveLikeLocalHeroSub:
      'Discover the best places and the best suggestions selected by locals.',
    essentials: 'Essentials',
    thingsToKnow: 'Things to know',
    googleRatingTitle: 'Enjoying your stay?',
    googleRatingSub: 'Share your experience on Google — it helps future guests.',
    rateOnGoogle: 'Rate on Google',
    reviewsOnGoogle: 'reviews on Google',
    installTitle: 'Quick access for your trip',
    installSub: 'Add Vailo to your home screen for one-tap access during your stay.',
    installCta: 'Add Vailo to Home Screen',
    installDismiss: 'Dismiss',
    installIosTitle: 'Add Vailo to your iPhone',
    installIosStep1: 'Tap the Share button at the bottom of Safari.',
    installIosStep2: 'Scroll down and tap “Add to Home Screen”.',
    installIosStep3: 'Tap Add — the Vailo icon will appear on your home screen.',
    installWaiting: 'Follow the prompt to install…',
    installSuccess: 'You can open Vailo from your home screen anytime.',
    gemsLayoutGroup: 'Local gems layout',
    gemsLayoutGrid: 'Two per row',
    gemsLayoutList: 'One per row',
    portalMenu: 'Menu',
    portalMenuClose: 'Close menu',
    houseGuide: 'House Guide',
    houseGuideSheetSub: 'Everything your host shared about the property.',
    houseGuideMenuSub:
      '{count} topics from your host — check-in, Wi‑Fi, appliances, house rules, daily needs, and more.',
    houseGuideMenuSubEmpty:
      'Your host hasn’t added a guide yet. Check-in, Wi‑Fi, and how-to tips for appliances will show here.',
    houseGuideEmpty: 'Your host has not added house guide details yet.',
    assistantProperty: 'AI Property Assistant',
    assistantPropertySub:
      'Ask about your stay anytime: Wi‑Fi, check-out, appliances (by model), house rules — or send a photo for help.',
  },
  el: {
    welcomeTo: 'Καλώς ήρθατε στο',
    map: 'Χάρτης',
    mapTitle: 'Η διαμονή σας',
    mapSubtitle: 'Τοποθεσία καταλύματος',
    openInMaps: 'Άνοιγμα στο Google Maps',
    getDirections: 'Οδηγίες',
    close: 'Κλείσιμο',
    propertyLocation: 'Τοποθεσία καταλύματος',
    liveLikeLocal: 'Ζήστε σαν ντόπιος',
    liveLikeLocalSub:
      'Οργανώστε την ημέρα σας με AI: εστιατόρια, παραλίες, μονοπάτια και αγαπημένα σημεία του οικοδεσπότη.',
    liveLikeLocalHero: 'Ζήστε σαν ντόπιος',
    liveLikeLocalHeroSub:
      'Ανακαλύψτε τα καλύτερα μέρη και τις καλύτερες προτάσεις από ντόπιους.',
    essentials: 'Βασικά',
    thingsToKnow: 'Χρήσιμες πληροφορίες',
    googleRatingTitle: 'Απολαμβάνετε τη διαμονή;',
    googleRatingSub: 'Αφήστε μια κριτική στο Google — βοηθάει τους επόμενους επισκέπτες.',
    rateOnGoogle: 'Βαθμολογία στο Google',
    reviewsOnGoogle: 'κριτικές στο Google',
    installTitle: 'Γρήγορη πρόσβαση για το ταξίδι σας',
    installSub: 'Προσθέστε το Vailo στην αρχική οθόνη για άμεση πρόσβαση.',
    installCta: 'Προσθήκη Vailo στην αρχική',
    installDismiss: 'Κλείσιμο',
    installIosTitle: 'Προσθήκη Vailo στο iPhone',
    installIosStep1: 'Πατήστε Κοινοποίηση στο κάτω μέρος του Safari.',
    installIosStep2: 'Κάντε scroll και επιλέξτε «Προσθήκη στην Αρχική Οθόνη».',
    installIosStep3: 'Πατήστε Προσθήκη — το εικονίδιο Vailo θα εμφανιστεί στην αρχική.',
    installWaiting: 'Ακολουθήστε τις οδηγίες εγκατάστασης…',
    installSuccess: 'Μπορείτε να ανοίξετε το Vailo από την αρχική οθόνη.',
    gemsLayoutGroup: 'Διάταξη τοπικών σημείων',
    gemsLayoutGrid: 'Δύο ανά σειρά',
    gemsLayoutList: 'Ένα ανά σειρά',
    portalMenu: 'Μενού',
    portalMenuClose: 'Κλείσιμο μενού',
    houseGuide: 'Οδηγός σπιτιού',
    houseGuideSheetSub: 'Ό,τι έχει μοιραστεί ο οικοδεσπότης για το κατάλυμα.',
    houseGuideMenuSub:
      '{count} ενότητες από τον οικοδεσπότη — check-in, Wi‑Fi, συσκευές, κανόνες, καθημερινές ανάγκες και άλλα.',
    houseGuideMenuSubEmpty:
      'Ο οικοδεσπότης δεν έχει προσθέσει ακόμα οδηγό. Εδώ θα εμφανιστούν check-in, Wi‑Fi και οδηγίες συσκευών.',
    houseGuideEmpty: 'Ο οικοδεσπότης δεν έχει προσθέσει ακόμα οδηγό σπιτιού.',
    assistantProperty: 'AI Βοηθός καταλύματος',
    assistantPropertySub:
      'Ρωτήστε για τη διαμονή σας: Wi‑Fi, check-out, συσκευές (ανά μοντέλο), κανόνες — ή στείλτε φωτογραφία για βοήθεια.',
  },
  de: {
    welcomeTo: 'Willkommen in',
    map: 'Karte',
    mapTitle: 'Ihr Aufenthalt',
    mapSubtitle: 'Standort der Unterkunft',
    openInMaps: 'In Google Maps öffnen',
    getDirections: 'Route',
    close: 'Schließen',
    propertyLocation: 'Standort der Unterkunft',
    liveLikeLocal: 'Leben wie ein Einheimischer',
    liveLikeLocalSub:
      'Planen Sie Ihren Tag mit KI: Restaurants, Strände, Wanderwege und Lieblingsorte Ihres Gastgebers.',
    liveLikeLocalHero: 'Leben wie ein Einheimischer',
    liveLikeLocalHeroSub:
      'Entdecken Sie die besten Orte und Empfehlungen, die Einheimische auswählen.',
    essentials: 'Wichtiges',
    thingsToKnow: 'Gut zu wissen',
    googleRatingTitle: 'Gefällt Ihnen der Aufenthalt?',
    googleRatingSub: 'Bewerten Sie uns auf Google — das hilft anderen Gästen.',
    rateOnGoogle: 'Auf Google bewerten',
    reviewsOnGoogle: 'Bewertungen auf Google',
    installTitle: 'Schnellzugriff für Ihre Reise',
    installSub: 'Fügen Sie Vailo zum Startbildschirm hinzu — ein Tipp während des Aufenthalts.',
    installCta: 'Vailo zum Startbildschirm',
    installDismiss: 'Schließen',
    installIosTitle: 'Vailo auf dem iPhone hinzufügen',
    installIosStep1: 'Tippen Sie unten in Safari auf Teilen.',
    installIosStep2: 'Scrollen Sie und wählen Sie „Zum Home-Bildschirm“.',
    installIosStep3: 'Tippen Sie Hinzufügen — das Vailo-Symbol erscheint auf dem Home-Bildschirm.',
    installWaiting: 'Folgen Sie der Installationsaufforderung…',
    installSuccess: 'Sie können Vailo jederzeit vom Home-Bildschirm öffnen.',
    gemsLayoutGroup: 'Layout lokaler Tipps',
    gemsLayoutGrid: 'Zwei pro Zeile',
    gemsLayoutList: 'Eine pro Zeile',
    portalMenu: 'Menü',
    portalMenuClose: 'Menü schließen',
    houseGuide: 'Hausführer',
    houseGuideSheetSub: 'Alles, was Ihr Gastgeber zur Unterkunft hinterlegt hat.',
    houseGuideMenuSub:
      '{count} Themen vom Gastgeber — Check-in, WLAN, Geräte, Hausregeln, Alltagsbedarf und mehr.',
    houseGuideMenuSubEmpty:
      'Noch kein Hausführer. Check-in, WLAN und Geräte-Anleitungen erscheinen hier, sobald der Gastgeber sie hinterlegt.',
    houseGuideEmpty: 'Ihr Gastgeber hat noch keinen Hausführer hinterlegt.',
    assistantProperty: 'KI-Unterkunftsassistent',
    assistantPropertySub:
      'Fragen zum Aufenthalt jederzeit: WLAN, Check-out, Geräte (nach Modell), Hausregeln — oder Foto zur Hilfe senden.',
  },
  fr: {
    welcomeTo: 'Bienvenue à',
    map: 'Carte',
    mapTitle: 'Votre séjour',
    mapSubtitle: 'Emplacement du logement',
    openInMaps: 'Ouvrir dans Google Maps',
    getDirections: 'Itinéraire',
    close: 'Fermer',
    propertyLocation: 'Emplacement du logement',
    liveLikeLocal: 'Vivre comme un local',
    liveLikeLocalSub:
      'Organisez votre journée avec l’IA : restaurants, plages, sentiers et adresses préférées de votre hôte.',
    liveLikeLocalHero: 'Vivre comme un local',
    liveLikeLocalHeroSub:
      'Découvrez les meilleurs endroits et suggestions choisies par les locaux.',
    essentials: 'Essentiels',
    thingsToKnow: 'À savoir',
    googleRatingTitle: 'Vous appréciez votre séjour ?',
    googleRatingSub: 'Laissez un avis sur Google — cela aide les futurs voyageurs.',
    rateOnGoogle: 'Noter sur Google',
    reviewsOnGoogle: 'avis sur Google',
    installTitle: 'Accès rapide pour votre séjour',
    installSub: 'Ajoutez Vailo à l’écran d’accueil pour un accès en un geste.',
    installCta: 'Ajouter Vailo à l’accueil',
    installDismiss: 'Fermer',
    installIosTitle: 'Ajouter Vailo sur iPhone',
    installIosStep1: 'Appuyez sur Partager en bas de Safari.',
    installIosStep2: 'Faites défiler et choisissez « Sur l’écran d’accueil ».',
    installIosStep3: 'Appuyez sur Ajouter — l’icône Vailo apparaîtra sur l’accueil.',
    installWaiting: 'Suivez l’invite d’installation…',
    installSuccess: 'Ouvrez Vailo depuis votre écran d’accueil à tout moment.',
    gemsLayoutGroup: 'Affichage des adresses',
    gemsLayoutGrid: 'Deux par ligne',
    gemsLayoutList: 'Une par ligne',
    portalMenu: 'Menu',
    portalMenuClose: 'Fermer le menu',
    houseGuide: 'Guide du logement',
    houseGuideSheetSub: 'Tout ce que votre hôte a partagé sur le logement.',
    houseGuideMenuSub:
      '{count} rubriques de l’hôte — arrivée, Wi‑Fi, appareils, règles, besoins du quotidien, etc.',
    houseGuideMenuSubEmpty:
      'Pas encore de guide. Arrivée, Wi‑Fi et mode d’emploi des appareils apparaîtront ici quand l’hôte les ajoute.',
    houseGuideEmpty: 'Votre hôte n’a pas encore ajouté de guide.',
    assistantProperty: 'Assistant IA du logement',
    assistantPropertySub:
      'Posez vos questions sur le séjour : Wi‑Fi, départ, appareils (par modèle), règles — ou envoyez une photo.',
  },
  it: {
    welcomeTo: 'Benvenuto a',
    map: 'Mappa',
    mapTitle: 'Il tuo soggiorno',
    mapSubtitle: 'Posizione della struttura',
    openInMaps: 'Apri in Google Maps',
    getDirections: 'Indicazioni',
    close: 'Chiudi',
    propertyLocation: 'Posizione della struttura',
    liveLikeLocal: 'Vivi come un local',
    liveLikeLocalSub:
      'Organizza la giornata con l’IA: ristoranti, spiagge, sentieri e i posti preferiti dell’host.',
    liveLikeLocalHero: 'Vivi come un local',
    liveLikeLocalHeroSub:
      'Scopri i migliori posti e i consigli scelti dai local.',
    essentials: 'Essenziali',
    thingsToKnow: 'Da sapere',
    googleRatingTitle: 'Ti piace il soggiorno?',
    googleRatingSub: 'Lascia una recensione su Google — aiuta i prossimi ospiti.',
    rateOnGoogle: 'Recensisci su Google',
    reviewsOnGoogle: 'recensioni su Google',
    installTitle: 'Accesso rapido per il viaggio',
    installSub: 'Aggiungi Vailo alla schermata Home per un accesso immediato.',
    installCta: 'Aggiungi Vailo alla Home',
    installDismiss: 'Chiudi',
    installIosTitle: 'Aggiungi Vailo su iPhone',
    installIosStep1: 'Tocca Condividi in basso in Safari.',
    installIosStep2: 'Scorri e scegli « Aggiungi a Home ».',
    installIosStep3: 'Tocca Aggiungi — l’icona Vailo apparirà sulla Home.',
    installWaiting: 'Segui il prompt di installazione…',
    installSuccess: 'Puoi aprire Vailo dalla schermata Home in qualsiasi momento.',
    gemsLayoutGroup: 'Layout consigli locali',
    gemsLayoutGrid: 'Due per riga',
    gemsLayoutList: 'Uno per riga',
    portalMenu: 'Menu',
    portalMenuClose: 'Chiudi menu',
    houseGuide: 'Guida della casa',
    houseGuideSheetSub: 'Tutto ciò che l’host ha condiviso sulla struttura.',
    houseGuideMenuSub:
      '{count} argomenti dall’host — check-in, Wi‑Fi, elettrodomestici, regole, bisogni quotidiani e altro.',
    houseGuideMenuSubEmpty:
      'Guida non ancora disponibile. Check-in, Wi‑Fi e istruzioni per gli elettrodomestici compariranno qui.',
    houseGuideEmpty: 'L’host non ha ancora aggiunto la guida.',
    assistantProperty: 'Assistente IA della struttura',
    assistantPropertySub:
      'Chiedi tutto sul soggiorno: Wi‑Fi, check-out, elettrodomestici (per modello), regole — o invia una foto.',
  },
};
