import type { BuiltinGuestLocale, GuestLocaleKey } from './guestLocale';

export const BUILTIN_PORTAL_MESSAGES: Record<BuiltinGuestLocale, Record<GuestLocaleKey, string>> = {
  en: {
    welcomeTo: 'Welcome to',
    map: 'Map',
    mapTitle: 'Your stay',
    mapSubtitle: 'Property location',
    openInMaps: 'Open in Google Maps',
    getDirections: 'Get directions',
    close: 'Close',
    propertyLocation: 'Property location',
    liveLikeLocal: 'Live like a local',
    liveLikeLocalSub:
      'Discover the best places and the best suggestions selected by locals.',
    liveLikeLocalHero: 'Live like a local',
    liveLikeLocalHeroSub:
      'Discover the best places and the best suggestions selected by locals.',
    checkInPromoTitle: 'Check in',
    checkInPromoSub: 'Complete your arrival details before you arrive.',
    checkInPromoContinue: 'Continue check-in',
    checkInPromoDoneTitle: 'You’re checked in',
    checkInPromoDoneSub: 'Your arrival details are with your host.',
    checkInBackToPortal: 'Back to guest portal',
    checkInNoteEyebrow: 'Did you know?',
    checkInNoteFree: 'Vailo is free to use throughout your vacation.',
    checkInNoteLocals: 'Skip the tourist traps and go where locals go.',
    checkInNoteAssistant:
      'A 24/7 assistant for Wi‑Fi, the house, and anything you need during your stay.',
    checkInNoteExcursions:
      'Excursions, boat trips, and activities you can browse and arrange from the portal.',
    checkInThanksTitle: 'Thank you',
    checkInThanksSub: 'Your check-in is complete. Your host has your arrival details.',
    checkInStartUsing: 'Start using Vailo',
    checkInRedirectHint: 'Opening your guest portal…',
    essentials: 'Essentials',
    thingsToKnow: 'Things to know',
    googleRatingTitle: 'Enjoying your stay?',
    googleRatingSub: 'Share your experience on Google — it helps future guests.',
    rateOnGoogle: 'Rate on Google',
    reviewsOnGoogle: 'reviews on Google',
    installTitle: 'Quick access for your trip',
    installSub: 'Add Vailo to your home screen for one-tap access during your stay.',
    installCta: 'Add Vailo to Home Screen',
    installDismiss: 'Dismiss',
    installIosTitle: 'Add Vailo to your iPhone',
    installIosStep1: 'Tap the Share button at the bottom of Safari.',
    installIosStep2: 'Scroll down and tap “Add to Home Screen”.',
    installIosStep3: 'Tap Add — the Vailo icon will appear on your home screen.',
    installWaiting: 'Follow the prompt to install…',
    installSuccess: 'You can open Vailo from your home screen anytime.',
    gemsLayoutGroup: 'Local gems layout',
    gemsLayoutGrid: 'Two per row',
    gemsLayoutList: 'One per row',
    portalMenu: 'Menu',
    portalMenuClose: 'Close menu',
    houseGuide: 'House Guide',
    houseGuideSheetSub: 'Everything your host shared about the property.',
    houseGuideMenuSub:
      '{count} topics from your host — check-in, Wi‑Fi, appliances, house rules, daily needs, and more.',
    houseGuideMenuSubEmpty:
      'Your host hasn’t added a guide yet. Check-in, Wi‑Fi, and how-to tips for appliances will show here.',
    houseGuideEmpty: 'Your host has not added house guide details yet.',
    assistantProperty: 'AI property chatbot',
    assistantPropertySub: 'Ask anything about the accommodation and your stay',
    savedLocalGemsTitle: 'Saved local gems',
    savedLocalGemsMenuSubEmpty: 'Places you save from Live like a local appear here — on this device only',
    savedLocalGemSavedToast: 'Saved! Open the menu — your saved items are under Saved local gems.',
    savedLocalGemRemoved: 'Removed from saved',
    savedLocalGemSaveAria: 'Save this place',
    savedLocalGemUnsaveAria: 'Remove from saved',
    savedLocalGemSaveLabel: 'Save',
    savedLocalGemSavedLabel: 'Saved',
    savedLocalGemRemoveLabel: 'Remove',
    savedLocalGemsDeviceNote: 'Saved only on this device — not shared with other guests or devices.',
    savedLocalGemsEmptyTitle: 'Nothing saved yet',
    savedLocalGemsEmptySub: 'Tap the bookmark on any Live like a local result to save it here.',
    savedLocalGemsNoMatch: 'No saved places match this category.',
    excursionsPromoTitle: 'Local excursions',
    excursionsPromoSub: '{count} experiences to book nearby',
    excursionsPromoFrom: 'From',
    excursionsPromoCta: 'Explore',
    excursionsPromoLoading: 'Finding experiences…',
    excursionsPromoSubEmpty: 'Curated day trips & local experiences',
    excursionAudiencePublic: 'Group tour',
    excursionAudiencePrivate: 'Private tour',
    excursionAudienceAll: 'All',
    excursionSortByPrice: 'Price · low to high',
    excursionProviderUsefulInfo: 'Useful info',
    excursionProviderAbout: 'About',
    excursionProviderFleet: 'Our fleet',
    excursionProviderFleetSpecs: 'Specifications',
    excursionProviderDetailsTap: 'Tap to view operator details',
    excursionProviderDetailsHide: 'Hide operator details',
    excursionProviderFleetSpecsTap: 'View specifications',
    excursionProviderFleetSpecsHide: 'Hide specifications',
    excursionReadMore: 'Read more',
    excursionReadLess: 'Read less',
  },
  el: {
    welcomeTo: 'Καλώς ήρθατε στο',
    map: 'Χάρτης',
    mapTitle: 'Η διαμονή σας',
    mapSubtitle: 'Τοποθεσία καταλύματος',
    openInMaps: 'Άνοιγμα στο Google Maps',
    getDirections: 'Οδηγίες',
    close: 'Κλείσιμο',
    propertyLocation: 'Τοποθεσία καταλύματος',
    liveLikeLocal: 'Ζήστε σαν ντόπιος',
    liveLikeLocalSub:
      'Ανακαλύψτε τα καλύτερα μέρη και τις καλύτερες προτάσεις από ντόπιους.',
    liveLikeLocalHero: 'Ζήστε σαν ντόπιος',
    liveLikeLocalHeroSub:
      'Ανακαλύψτε τα καλύτερα μέρη και τις καλύτερες προτάσεις από ντόπιους.',
    checkInPromoTitle: 'Check-in',
    checkInPromoSub: 'Συμπληρώστε τα στοιχεία άφιξης πριν φτάσετε.',
    checkInPromoContinue: 'Συνέχεια check-in',
    checkInPromoDoneTitle: 'Έχετε κάνει check-in',
    checkInPromoDoneSub: 'Τα στοιχεία άφιξης έχουν σταλεί στον οικοδεσπότη.',
    checkInBackToPortal: 'Επιστροφή στην πύλη επισκεπτών',
    checkInNoteEyebrow: 'Το ήξερες;',
    checkInNoteFree: 'Το Vailo είναι δωρεάν σε όλες σας τις διακοπές.',
    checkInNoteLocals: 'Αποφύγετε τις τουριστικές παγίδες και πηγαίνετε εκεί που πάνε οι ντόπιοι.',
    checkInNoteAssistant:
      'Βοηθός 24/7 για το Wi‑Fi, το σπίτι και ό,τι χρειαστείτε στη διαμονή σας.',
    checkInNoteExcursions:
      'Εκδρομές, βόλτες με σκάφος και δραστηριότητες που μπορείτε να δείτε και να κλείσετε από την πύλη.',
    checkInThanksTitle: 'Ευχαριστούμε',
    checkInThanksSub: 'Το check-in ολοκληρώθηκε. Ο οικοδεσπότης έχει τα στοιχεία άφιξής σας.',
    checkInStartUsing: 'Ξεκινήστε το Vailo',
    checkInRedirectHint: 'Άνοιγμα της πύλης επισκεπτών…',
    essentials: 'Βασικά',
    thingsToKnow: 'Χρήσιμες πληροφορίες',
    googleRatingTitle: 'Απολαμβάνετε τη διαμονή;',
    googleRatingSub: 'Αφήστε μια κριτική στο Google — βοηθάει τους επόμενους επισκέπτες.',
    rateOnGoogle: 'Βαθμολογία στο Google',
    reviewsOnGoogle: 'κριτικές στο Google',
    installTitle: 'Γρήγορη πρόσβαση για το ταξίδι σας',
    installSub: 'Προσθέστε το Vailo στην αρχική οθόνη για άμεση πρόσβαση.',
    installCta: 'Προσθήκη Vailo στην αρχική',
    installDismiss: 'Κλείσιμο',
    installIosTitle: 'Προσθήκη Vailo στο iPhone',
    installIosStep1: 'Πατήστε Κοινοποίηση στο κάτω μέρος του Safari.',
    installIosStep2: 'Κάντε scroll και επιλέξτε «Προσθήκη στην Αρχική Οθόνη».',
    installIosStep3: 'Πατήστε Προσθήκη — το εικονίδιο Vailo θα εμφανιστεί στην αρχική.',
    installWaiting: 'Ακολουθήστε τις οδηγίες εγκατάστασης…',
    installSuccess: 'Μπορείτε να ανοίξετε το Vailo από την αρχική οθόνη.',
    gemsLayoutGroup: 'Διάταξη τοπικών σημείων',
    gemsLayoutGrid: 'Δύο ανά σειρά',
    gemsLayoutList: 'Ένα ανά σειρά',
    portalMenu: 'Μενού',
    portalMenuClose: 'Κλείσιμο μενού',
    houseGuide: 'Οδηγός σπιτιού',
    houseGuideSheetSub: 'Ό,τι έχει μοιραστεί ο οικοδεσπότης για το κατάλυμα.',
    houseGuideMenuSub:
      '{count} ενότητες από τον οικοδεσπότη — check-in, Wi‑Fi, συσκευές, κανόνες, καθημερινές ανάγκες και άλλα.',
    houseGuideMenuSubEmpty:
      'Ο οικοδεσπότης δεν έχει προσθέσει ακόμα οδηγό. Εδώ θα εμφανιστούν check-in, Wi‑Fi και οδηγίες συσκευών.',
    houseGuideEmpty: 'Ο οικοδεσπότης δεν έχει προσθέσει ακόμα οδηγό σπιτιού.',
    assistantProperty: 'AI chatbot καταλύματος',
    assistantPropertySub: 'Ρωτήστε οτιδήποτε για το κατάλυμα και τη διαμονή σας',
    savedLocalGemsTitle: 'Αποθηκευμένα τοπικά σημεία',
    savedLocalGemsMenuSubEmpty: 'Τα σημεία που αποθηκεύετε από το «Ζήστε σαν ντόπιος» εμφανίζονται εδώ — μόνο σε αυτή τη συσκευή',
    savedLocalGemSavedToast: 'Αποθηκεύτηκε! Ανοίξτε το μενού — τα αποθηκευμένα βρίσκονται στα «Αποθηκευμένα τοπικά σημεία».',
    savedLocalGemRemoved: 'Αφαιρέθηκε από τα αποθηκευμένα',
    savedLocalGemSaveAria: 'Αποθήκευση αυτού του μέρους',
    savedLocalGemUnsaveAria: 'Αφαίρεση από τα αποθηκευμένα',
    savedLocalGemSaveLabel: 'Αποθήκευση',
    savedLocalGemSavedLabel: 'Αποθηκεύτηκε',
    savedLocalGemRemoveLabel: 'Αφαίρεση',
    savedLocalGemsDeviceNote: 'Αποθηκεύονται μόνο σε αυτή τη συσκευή — δεν κοινοποιούνται με άλλους επισκέπτες ή συσκευές.',
    savedLocalGemsEmptyTitle: 'Δεν υπάρχουν αποθηκευμένα ακόμα',
    savedLocalGemsEmptySub: 'Πατήστε το σελιδοδείκτη σε οποιοδήποτε αποτέλεσμα «Ζήστε σαν ντόπιος» για να το αποθηκεύσετε εδώ.',
    savedLocalGemsNoMatch: 'Κανένα αποθηκευμένο μέρος δεν ταιριάζει σε αυτή την κατηγορία.',
    excursionsPromoTitle: 'Τοπικές εκδρομές',
    excursionsPromoSub: '{count} εμπειρίες για κράτηση κοντά σας',
    excursionsPromoFrom: 'Από',
    excursionsPromoCta: 'Δείτε',
    excursionsPromoLoading: 'Φόρτωση εμπειριών…',
    excursionsPromoSubEmpty: 'Οργανωμένες εκδρομές & τοπικές εμπειρίες',
    excursionAudiencePublic: 'Ομαδική εκδρομή',
    excursionAudiencePrivate: 'Ιδιωτική εκδρομή',
    excursionAudienceAll: 'Όλες',
    excursionSortByPrice: 'Τιμή · χαμηλή → υψηλή',
    excursionProviderUsefulInfo: 'Χρήσιμες πληροφορίες',
    excursionProviderAbout: 'Σχετικά με',
    excursionProviderFleet: 'Στόλος',
    excursionProviderFleetSpecs: 'Τεχνικά χαρακτηριστικά',
    excursionProviderDetailsTap: 'Πατήστε για λεπτομέρειες παρόχου',
    excursionProviderDetailsHide: 'Απόκρυψη λεπτομερειών',
    excursionProviderFleetSpecsTap: 'Προβολή χαρακτηριστικών',
    excursionProviderFleetSpecsHide: 'Απόκρυψη χαρακτηριστικών',
    excursionReadMore: 'Διαβάστε περισσότερα',
    excursionReadLess: 'Λιγότερα',
  },
  de: {
    welcomeTo: 'Willkommen in',
    map: 'Karte',
    mapTitle: 'Ihr Aufenthalt',
    mapSubtitle: 'Standort der Unterkunft',
    openInMaps: 'In Google Maps öffnen',
    getDirections: 'Route',
    close: 'Schließen',
    propertyLocation: 'Standort der Unterkunft',
    liveLikeLocal: 'Leben wie ein Einheimischer',
    liveLikeLocalSub:
      'Entdecken Sie die besten Orte und Empfehlungen, die Einheimische auswählen.',
    liveLikeLocalHero: 'Leben wie ein Einheimischer',
    liveLikeLocalHeroSub:
      'Entdecken Sie die besten Orte und Empfehlungen, die Einheimische auswählen.',
    checkInPromoTitle: 'Check-in',
    checkInPromoSub: 'Ergänzen Sie Ihre Anreisedaten vor der Ankunft.',
    checkInPromoContinue: 'Check-in fortsetzen',
    checkInPromoDoneTitle: 'Sie sind eingecheckt',
    checkInPromoDoneSub: 'Ihre Anreisedaten liegen dem Gastgeber vor.',
    checkInBackToPortal: 'Zurück zum Gästeportal',
    checkInNoteEyebrow: 'Wussten Sie schon?',
    checkInNoteFree: 'Vailo ist während Ihres gesamten Urlaubs kostenlos.',
    checkInNoteLocals: 'Keine Touristenfallen — gehen Sie dorthin, wo Einheimische hingehen.',
    checkInNoteAssistant:
      'Ein 24/7-Assistent für WLAN, das Haus und alles, was Sie für Ihren Aufenthalt brauchen.',
    checkInNoteExcursions:
      'Ausflüge, Bootsfahrten und Aktivitäten — direkt im Portal entdecken und buchen.',
    checkInThanksTitle: 'Vielen Dank',
    checkInThanksSub: 'Ihr Check-in ist abgeschlossen. Ihr Gastgeber hat Ihre Anreisedaten.',
    checkInStartUsing: 'Vailo jetzt nutzen',
    checkInRedirectHint: 'Ihr Gästeportal wird geöffnet…',
    essentials: 'Wichtiges',
    thingsToKnow: 'Gut zu wissen',
    googleRatingTitle: 'Gefällt Ihnen der Aufenthalt?',
    googleRatingSub: 'Bewerten Sie uns auf Google — das hilft anderen Gästen.',
    rateOnGoogle: 'Auf Google bewerten',
    reviewsOnGoogle: 'Bewertungen auf Google',
    installTitle: 'Schnellzugriff für Ihre Reise',
    installSub: 'Fügen Sie Vailo zum Startbildschirm hinzu — ein Tipp während des Aufenthalts.',
    installCta: 'Vailo zum Startbildschirm',
    installDismiss: 'Schließen',
    installIosTitle: 'Vailo auf dem iPhone hinzufügen',
    installIosStep1: 'Tippen Sie unten in Safari auf Teilen.',
    installIosStep2: 'Scrollen Sie und wählen Sie „Zum Home-Bildschirm“.',
    installIosStep3: 'Tippen Sie Hinzufügen — das Vailo-Symbol erscheint auf dem Home-Bildschirm.',
    installWaiting: 'Folgen Sie der Installationsaufforderung…',
    installSuccess: 'Sie können Vailo jederzeit vom Home-Bildschirm öffnen.',
    gemsLayoutGroup: 'Layout lokaler Tipps',
    gemsLayoutGrid: 'Zwei pro Zeile',
    gemsLayoutList: 'Eine pro Zeile',
    portalMenu: 'Menü',
    portalMenuClose: 'Menü schließen',
    houseGuide: 'Hausführer',
    houseGuideSheetSub: 'Alles, was Ihr Gastgeber zur Unterkunft hinterlegt hat.',
    houseGuideMenuSub:
      '{count} Themen vom Gastgeber — Check-in, WLAN, Geräte, Hausregeln, Alltagsbedarf und mehr.',
    houseGuideMenuSubEmpty:
      'Noch kein Hausführer. Check-in, WLAN und Geräte-Anleitungen erscheinen hier, sobald der Gastgeber sie hinterlegt.',
    houseGuideEmpty: 'Ihr Gastgeber hat noch keinen Hausführer hinterlegt.',
    assistantProperty: 'KI-Chatbot der Unterkunft',
    assistantPropertySub: 'Fragen Sie alles zur Unterkunft und Ihrem Aufenthalt',
    savedLocalGemsTitle: 'Gespeicherte lokale Tipps',
    savedLocalGemsMenuSubEmpty: 'Orte aus „Leben wie ein Einheimischer“ erscheinen hier — nur auf diesem Gerät',
    savedLocalGemSavedToast: 'Gespeichert! Öffnen Sie das Menü — unter „Gespeicherte lokale Tipps“.',
    savedLocalGemRemoved: 'Aus Gespeicherten entfernt',
    savedLocalGemSaveAria: 'Diesen Ort speichern',
    savedLocalGemUnsaveAria: 'Aus Gespeicherten entfernen',
    savedLocalGemSaveLabel: 'Speichern',
    savedLocalGemSavedLabel: 'Gespeichert',
    savedLocalGemRemoveLabel: 'Entfernen',
    savedLocalGemsDeviceNote: 'Nur auf diesem Gerät gespeichert — nicht mit anderen Gästen oder Geräten geteilt.',
    savedLocalGemsEmptyTitle: 'Noch nichts gespeichert',
    savedLocalGemsEmptySub: 'Tippen Sie auf das Lesezeichen bei einem Ergebnis aus „Leben wie ein Einheimischer“.',
    savedLocalGemsNoMatch: 'Keine gespeicherten Orte in dieser Kategorie.',
    excursionsPromoTitle: 'Lokale Ausflüge',
    excursionsPromoSub: '{count} Erlebnisse in der Nähe buchbar',
    excursionsPromoFrom: 'Ab',
    excursionsPromoCta: 'Entdecken',
    excursionsPromoLoading: 'Erlebnisse werden geladen…',
    excursionsPromoSubEmpty: 'Ausflüge & lokale Erlebnisse',
    excursionAudiencePublic: 'Gruppentour',
    excursionAudiencePrivate: 'Privattour',
    excursionAudienceAll: 'Alle',
    excursionSortByPrice: 'Preis · niedrig bis hoch',
    excursionProviderUsefulInfo: 'Nützliche Infos',
    excursionProviderAbout: 'Über',
    excursionProviderFleet: 'Unsere Flotte',
    excursionProviderFleetSpecs: 'Technische Daten',
    excursionProviderDetailsTap: 'Tippen für Anbieterdetails',
    excursionProviderDetailsHide: 'Details ausblenden',
    excursionProviderFleetSpecsTap: 'Technische Daten anzeigen',
    excursionProviderFleetSpecsHide: 'Technische Daten ausblenden',
    excursionReadMore: 'Mehr lesen',
    excursionReadLess: 'Weniger anzeigen',
  },
  fr: {
    welcomeTo: 'Bienvenue à',
    map: 'Carte',
    mapTitle: 'Votre séjour',
    mapSubtitle: 'Emplacement du logement',
    openInMaps: 'Ouvrir dans Google Maps',
    getDirections: 'Itinéraire',
    close: 'Fermer',
    propertyLocation: 'Emplacement du logement',
    liveLikeLocal: 'Vivre comme un local',
    liveLikeLocalSub:
      'Découvrez les meilleurs endroits et suggestions choisies par les locaux.',
    liveLikeLocalHero: 'Vivre comme un local',
    liveLikeLocalHeroSub:
      'Découvrez les meilleurs endroits et suggestions choisies par les locaux.',
    checkInPromoTitle: 'Enregistrement',
    checkInPromoSub: 'Complétez vos informations d’arrivée avant de venir.',
    checkInPromoContinue: 'Continuer l’enregistrement',
    checkInPromoDoneTitle: 'Vous êtes enregistré',
    checkInPromoDoneSub: 'Vos informations d’arrivée ont été transmises à votre hôte.',
    checkInBackToPortal: 'Retour au portail invité',
    checkInNoteEyebrow: 'Le saviez-vous ?',
    checkInNoteFree: 'Vailo est gratuit pendant toutes vos vacances.',
    checkInNoteLocals: 'Évitez les pièges à touristes et allez là où vont les locaux.',
    checkInNoteAssistant:
      'Un assistant 24h/24 pour le Wi‑Fi, la maison et tout ce dont vous avez besoin.',
    checkInNoteExcursions:
      'Excursions, sorties en bateau et activités à parcourir et réserver depuis le portail.',
    checkInThanksTitle: 'Merci',
    checkInThanksSub: 'Votre enregistrement est terminé. Votre hôte a vos informations d’arrivée.',
    checkInStartUsing: 'Commencer à utiliser Vailo',
    checkInRedirectHint: 'Ouverture de votre portail invité…',
    essentials: 'Essentiels',
    thingsToKnow: 'À savoir',
    googleRatingTitle: 'Vous appréciez votre séjour ?',
    googleRatingSub: 'Laissez un avis sur Google — cela aide les futurs voyageurs.',
    rateOnGoogle: 'Noter sur Google',
    reviewsOnGoogle: 'avis sur Google',
    installTitle: 'Accès rapide pour votre séjour',
    installSub: 'Ajoutez Vailo à l’écran d’accueil pour un accès en un geste.',
    installCta: 'Ajouter Vailo à l’accueil',
    installDismiss: 'Fermer',
    installIosTitle: 'Ajouter Vailo sur iPhone',
    installIosStep1: 'Appuyez sur Partager en bas de Safari.',
    installIosStep2: 'Faites défiler et choisissez « Sur l’écran d’accueil ».',
    installIosStep3: 'Appuyez sur Ajouter — l’icône Vailo apparaîtra sur l’accueil.',
    installWaiting: 'Suivez l’invite d’installation…',
    installSuccess: 'Ouvrez Vailo depuis votre écran d’accueil à tout moment.',
    gemsLayoutGroup: 'Affichage des adresses',
    gemsLayoutGrid: 'Deux par ligne',
    gemsLayoutList: 'Une par ligne',
    portalMenu: 'Menu',
    portalMenuClose: 'Fermer le menu',
    houseGuide: 'Guide du logement',
    houseGuideSheetSub: 'Tout ce que votre hôte a partagé sur le logement.',
    houseGuideMenuSub:
      '{count} rubriques de l’hôte — arrivée, Wi‑Fi, appareils, règles, besoins du quotidien, etc.',
    houseGuideMenuSubEmpty:
      'Pas encore de guide. Arrivée, Wi‑Fi et mode d’emploi des appareils apparaîtront ici quand l’hôte les ajoute.',
    houseGuideEmpty: 'Votre hôte n’a pas encore ajouté de guide.',
    assistantProperty: 'Chatbot IA du logement',
    assistantPropertySub: 'Posez toutes vos questions sur le logement et votre séjour',
    savedLocalGemsTitle: 'Adresses enregistrées',
    savedLocalGemsMenuSubEmpty: 'Les lieux enregistrés depuis « Vivre comme un local » apparaissent ici — sur cet appareil uniquement',
    savedLocalGemSavedToast: 'Enregistré ! Ouvrez le menu — sous « Adresses enregistrées ».',
    savedLocalGemRemoved: 'Retiré des enregistrements',
    savedLocalGemSaveAria: 'Enregistrer ce lieu',
    savedLocalGemUnsaveAria: 'Retirer des enregistrements',
    savedLocalGemSaveLabel: 'Enregistrer',
    savedLocalGemSavedLabel: 'Enregistré',
    savedLocalGemRemoveLabel: 'Retirer',
    savedLocalGemsDeviceNote: 'Enregistré uniquement sur cet appareil — non partagé avec d’autres voyageurs ou appareils.',
    savedLocalGemsEmptyTitle: 'Rien enregistré pour l’instant',
    savedLocalGemsEmptySub: 'Appuyez sur le signet sur un résultat « Vivre comme un local » pour l’enregistrer ici.',
    savedLocalGemsNoMatch: 'Aucun lieu enregistré dans cette catégorie.',
    excursionsPromoTitle: 'Excursions locales',
    excursionsPromoSub: '{count} expériences à réserver à proximité',
    excursionsPromoFrom: 'Dès',
    excursionsPromoCta: 'Explorer',
    excursionsPromoLoading: 'Chargement des expériences…',
    excursionsPromoSubEmpty: 'Excursions & expériences locales',
    excursionAudiencePublic: 'Excursion en groupe',
    excursionAudiencePrivate: 'Excursion privée',
    excursionAudienceAll: 'Toutes',
    excursionSortByPrice: 'Prix · croissant',
    excursionProviderUsefulInfo: 'Infos pratiques',
    excursionProviderAbout: 'À propos de',
    excursionProviderFleet: 'Notre flotte',
    excursionProviderFleetSpecs: 'Caractéristiques',
    excursionProviderDetailsTap: 'Appuyez pour voir l’opérateur',
    excursionProviderDetailsHide: 'Masquer les détails',
    excursionProviderFleetSpecsTap: 'Voir les caractéristiques',
    excursionProviderFleetSpecsHide: 'Masquer les caractéristiques',
    excursionReadMore: 'Lire la suite',
    excursionReadLess: 'Réduire',
  },
  it: {
    welcomeTo: 'Benvenuto a',
    map: 'Mappa',
    mapTitle: 'Il tuo soggiorno',
    mapSubtitle: 'Posizione della struttura',
    openInMaps: 'Apri in Google Maps',
    getDirections: 'Indicazioni',
    close: 'Chiudi',
    propertyLocation: 'Posizione della struttura',
    liveLikeLocal: 'Vivi come un local',
    liveLikeLocalSub:
      'Scopri i migliori posti e i consigli scelti dai local.',
    liveLikeLocalHero: 'Vivi come un local',
    liveLikeLocalHeroSub:
      'Scopri i migliori posti e i consigli scelti dai local.',
    checkInPromoTitle: 'Check-in',
    checkInPromoSub: 'Completa i dettagli di arrivo prima di arrivare.',
    checkInPromoContinue: 'Continua il check-in',
    checkInPromoDoneTitle: 'Check-in completato',
    checkInPromoDoneSub: 'I dettagli di arrivo sono stati inviati all’host.',
    checkInBackToPortal: 'Torna al portale ospiti',
    checkInNoteEyebrow: 'Lo sapevi?',
    checkInNoteFree: 'Vailo è gratis per tutta la vacanza.',
    checkInNoteLocals: 'Niente trappole per turisti — vai dove vanno i local.',
    checkInNoteAssistant:
      'Un assistente 24/7 per il Wi‑Fi, la casa e tutto ciò che ti serve durante il soggiorno.',
    checkInNoteExcursions:
      'Escursioni, gite in barca e attività da scoprire e prenotare dal portale.',
    checkInThanksTitle: 'Grazie',
    checkInThanksSub: 'Il check-in è completo. L’host ha i tuoi dettagli di arrivo.',
    checkInStartUsing: 'Inizia a usare Vailo',
    checkInRedirectHint: 'Apertura del portale ospiti…',
    essentials: 'Essenziali',
    thingsToKnow: 'Da sapere',
    googleRatingTitle: 'Ti piace il soggiorno?',
    googleRatingSub: 'Lascia una recensione su Google — aiuta i prossimi ospiti.',
    rateOnGoogle: 'Recensisci su Google',
    reviewsOnGoogle: 'recensioni su Google',
    installTitle: 'Accesso rapido per il viaggio',
    installSub: 'Aggiungi Vailo alla schermata Home per un accesso immediato.',
    installCta: 'Aggiungi Vailo alla Home',
    installDismiss: 'Chiudi',
    installIosTitle: 'Aggiungi Vailo su iPhone',
    installIosStep1: 'Tocca Condividi in basso in Safari.',
    installIosStep2: 'Scorri e scegli « Aggiungi a Home ».',
    installIosStep3: 'Tocca Aggiungi — l’icona Vailo apparirà sulla Home.',
    installWaiting: 'Segui il prompt di installazione…',
    installSuccess: 'Puoi aprire Vailo dalla schermata Home in qualsiasi momento.',
    gemsLayoutGroup: 'Layout consigli locali',
    gemsLayoutGrid: 'Due per riga',
    gemsLayoutList: 'Uno per riga',
    portalMenu: 'Menu',
    portalMenuClose: 'Chiudi menu',
    houseGuide: 'Guida della casa',
    houseGuideSheetSub: 'Tutto ciò che l’host ha condiviso sulla struttura.',
    houseGuideMenuSub:
      '{count} argomenti dall’host — check-in, Wi‑Fi, elettrodomestici, regole, bisogni quotidiani e altro.',
    houseGuideMenuSubEmpty:
      'Guida non ancora disponibile. Check-in, Wi‑Fi e istruzioni per gli elettrodomestici compariranno qui.',
    houseGuideEmpty: 'L’host non ha ancora aggiunto la guida.',
    assistantProperty: 'Chatbot IA della struttura',
    assistantPropertySub: 'Chiedi qualsiasi cosa sulla struttura e sul tuo soggiorno',
    savedLocalGemsTitle: 'Consigli locali salvati',
    savedLocalGemsMenuSubEmpty: 'I posti salvati da « Vivi come un local » compaiono qui — solo su questo dispositivo',
    savedLocalGemSavedToast: 'Salvato! Apri il menu — sotto « Consigli locali salvati ».',
    savedLocalGemRemoved: 'Rimosso dai salvati',
    savedLocalGemSaveAria: 'Salva questo posto',
    savedLocalGemUnsaveAria: 'Rimuovi dai salvati',
    savedLocalGemSaveLabel: 'Salva',
    savedLocalGemSavedLabel: 'Salvato',
    savedLocalGemRemoveLabel: 'Rimuovi',
    savedLocalGemsDeviceNote: 'Salvato solo su questo dispositivo — non condiviso con altri ospiti o dispositivi.',
    savedLocalGemsEmptyTitle: 'Nessun salvataggio ancora',
    savedLocalGemsEmptySub: 'Tocca il segnalibro su un risultato « Vivi come un local » per salvarlo qui.',
    savedLocalGemsNoMatch: 'Nessun posto salvato in questa categoria.',
    excursionsPromoTitle: 'Escursioni locali',
    excursionsPromoSub: '{count} esperienze prenotabili nelle vicinanze',
    excursionsPromoFrom: 'Da',
    excursionsPromoCta: 'Scopri',
    excursionsPromoLoading: 'Caricamento esperienze…',
    excursionsPromoSubEmpty: 'Escursioni ed esperienze locali',
    excursionAudiencePublic: 'Tour di gruppo',
    excursionAudiencePrivate: 'Tour privato',
    excursionAudienceAll: 'Tutte',
    excursionSortByPrice: 'Prezzo · dal più basso',
    excursionProviderUsefulInfo: 'Informazioni utili',
    excursionProviderAbout: 'Informazioni su',
    excursionProviderFleet: 'La nostra flotta',
    excursionProviderFleetSpecs: 'Specifiche tecniche',
    excursionProviderDetailsTap: 'Tocca per i dettagli dell’operatore',
    excursionProviderDetailsHide: 'Nascondi dettagli',
    excursionProviderFleetSpecsTap: 'Mostra specifiche',
    excursionProviderFleetSpecsHide: 'Nascondi specifiche',
    excursionReadMore: 'Leggi di più',
    excursionReadLess: 'Mostra meno',
  },
};
